### ISSUE TITLE
Naming table/graph results 

### ISSUE THREAD

**Issue by quique05** [QuriQuant/qq-pat#1]
It woud be very useful to identify with a name any table or graph that qq-pat generates.

**Comment by danielfppps** [comment]
Do you mean a title on the graphs/tables? or something different?

**Comment by quique05** [comment]
That's exactly what I mean. I would like to know which is the systems name, or stock, or pair, or other title I want that identify the the graph/table I'm seen. 

Thank you very much Daniel :)

**Comment by danielfppps** [comment]
The option to add titles has now been included on the latest release. You can do this by initializing the library with a given set of titles. For example:

analyzer = qqpat.Analizer(data, column_type='price', titles=["appl", "spy", "ibm"])

If you don't define the titles then no titles are used.
