### ISSUE TITLE
Making it work with matplotlib<1.5

### ISSUE THREAD

**Issue by etyurin** [QuriQuant/qq-pat#3]
One suggestion: your package depends on matplotlib 1.5.x - while most Linux distributions out there don't carry it. It is coming in the next Ubuntu release - Xenial. And installing it from pip didn't work for me - due to missing libraries etc.

Anyhow, turns out only two small changes are needed to make it work on my matplotlib 1.3.1. Comment out these lines and add fixed colors list in plot_analysis_rolling() and plot_analysis_returns()

```
    # color_cycle = ax1._get_lines.prop_cycler
    # colors = []
    colors = ['b','g','r','c','m','y','k']

    # for i, color in enumerate(color_cycle):
    #    if i<len(data.columns):
    #        colors.append(color['color'])
    #    else:
    #        break
```

**Comment by danielfppps** [comment]
Thanks for your suggestion. The problem with this change is that imposes a small and limited set of color on graphs. A valid solution should be a proper color cycler replacement where colors are not from a small finite set.
